language: cpp

os:
  - linux
  - osx
  
# Run tests
script:
  - g++ -std=c++17 -Wall -Wextra -pedantic -o testsVector ./code/SetVector.cpp ./code/mainTests.cpp  
  - ./testsVector.out
  - g++ -std=c++17 -Wall -Wextra -pedantic -o testsVectorEspecific ./code/SetVector.cpp ./code/mainTestsEspecific.cpp
  - ./testsVectorEspecific.out
