language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  
# Run tests
script:
  - g++ -std=c++17 -Wall -Wextra -pedantic -o testsVector ./code/SetVector.cpp ./code/mainTests.cpp  
  - ./testsVector.out
  - g++ -std=c++17 -Wall -Wextra -pedantic -o testsVectorEspecific ./code/SetVector.cpp ./code/mainTestsEspecific.cpp
  - ./testsVectorEspecific.out
