language: cpp

os:
  - linux
  - osx
  
# Run tests
script:
  - g++ -std=c++17 -Wall -Wextra -pedantic -o testsVector.exe /code/SetVector.cpp /code/mainTests.cpp  
  - ./testsVector.exe
  - g++ -std=c++17 -Wall -Wextra -pedantic -o testsVectorEspecific.exe /code/SetVector.cpp /code/mainTestsEspecific.cpp
  - ./testsVectorEspecific.exe
